---
title: "Feedback and History of Changes"
author: "Johan Larsson"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: united
    highlight: tango
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  cache = FALSE,
  fig.align = "center",
  fig.width = 5,
  fig.height = 4,
  dev = "png"
)
options(scipen = 999)
```

# Fall 2021

### Feedback from Last Run

Among the 19 respondents, one gave the course a "sufficient" score, 4 "very
good", and 14 "excellent". Most of the respondents were equally positive for
most other questions except for the one regarding literature, which was regarded
as "sufficient" by 2, "good" by 6, "very good" by 4, "excellent" by 5, and
"don't know" by 2. Everyone except one respondent reported that they spent
between 0 and 17 hours per week on the course.

When it comes to constructive feedback, here are a few things that students
thought might improve the course:

- coding videos,
- more time for the project,
- more theory and tools for data wrangling,
- better overview of course content, and
- less assignments and quizzes in general.

### Changes

- The R Markdown template and introduction have been separated into two
  documents and the introduction has been revised, including a new portion on
  how to make tables using `knitr::kable()`.
- The assignments and project no longer use anonymous peer reviews since that
  made it impossible for both instructors and students to provide annotated
  feedback.
- All of the rubrics have been rewritten and made specific to each assignment.
- Submitting `.R` and `.Rmd` files has been made possible.
- Assignment 2 has been revised slightly.
- Assignment 3 has been completely rewritten, using a new data set.
- Assignment 4 has been revised majorly.
- Questions in the assignments have been made a little more free to encourage
  creativity.
- Project requirements have been modified slightly.
- All of the practice quizzes now have a hand-in exercise.
- Several questions on the quizzes have been modified. Some have been removed.
- The **ggmosaic** package is recommended instead of **productplots** in most
  places.

# Spring 2021

### Feedback from Last Run

Feedback on the course was positive across all items in the course evaluation.
We received one specific request, which was to make the workshops (help 
sessions) weekly instead of bi-weekly.

### Changes

- Several new *Worked Examples* have been added to the course. The source code
  for all of these worked examples has also been made available on the GitHub
  repository for the course.
- All of the reading assignments have been converted into quizzes.
- The initial "Post a Visualization" assignment has been removed.
- The workshops have been made weekly (instead of bi-weekly), and the duration
  has been shortened to one hour.
- Prerequisites and requirements for the course modules have been removed so
  that all the course content is now accessible right away.

# Fall 2020

First time for the course.


