---
title: "Change Log"
author: "Johan Larsson"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2:
    toc: true
    toc_float: true
    highlight: pygments
    global_numbering: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  cache = FALSE,
  fig.align = "center",
  fig.width = 5,
  fig.height = 4,
  dev = "png"
)
options(scipen = 999)
```

# Fall 2023

- The course literature was changed. As a consequence, all of the reading quizzes were remade too.

# Fall 2022

- The Chile Plebiscite worked example was removed and replaced with a new
  worked example called "Food for Thought", which is about food expenditure
  for Spanish households.
- A new page about figure formatting has been included in the course, which
  primarily covers good practices when it comes to writing captions.
- The course repository on github was completely reorganized to make it
  easier to navigate.
- All of the worked examples and pages were re-designed with better syntax
  highlighting among other things.
- Several typos were corrected throughout the material.

# Spring 2022

- Three of the lecture videos have been replaced
- A new practice quiz, "Practice: Getting Started with ggplot2" has been added
- All parts of the course that have to do with mapping now uses simple features
  instead of the standard polygon map approach.
- The quizzes are once again completely automatically graded.
- Several quizzes have been revised, often simplified.
- The **productplots** package has been replaced with the **ggmosaic** package.

# Fall 2021

- The R Markdown template and introduction have been separated into two
  documents and the introduction has been revised, including a new portion on
  how to make tables using `knitr::kable()`.
- The assignments and project no longer use anonymous peer reviews since that
  made it impossible for both instructors and students to provide annotated
  feedback.
- All of the rubrics have been rewritten and made specific to each assignment.
- Submitting `.R` and `.Rmd` files has been made possible.
- Assignment 2 has been revised slightly.
- Assignment 3 has been completely rewritten, using a new data set.
- Assignment 4 has been revised majorly.
- Questions in the assignments have been made a little more free to encourage
  creativity.
- Project requirements have been modified slightly.
- All of the practice quizzes now have a hand-in exercise.
- Several questions on the quizzes have been modified. Some have been removed.
- The **ggmosaic** package is recommended instead of **productplots** in most
  places.
- Several coding videos have been added.

# Spring 2021

- Several new *Worked Examples* have been added to the course. The source code
  for all of these worked examples has also been made available on the GitHub
  repository for the course.
- All of the reading assignments have been converted into quizzes.
- The initial "Post a Visualization" assignment has been removed.
- The workshops have been made weekly (instead of bi-weekly), and the duration
  has been shortened to one hour.
- Prerequisites and requirements for the course modules have been removed so
  that all the course content is now accessible right away.

# Fall 2020

First time for the course.


