---
title: "Course Feedback"
author: "Johan Larsson"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  bookdown::html_document2:
    toc: true
    toc_float: true
    highlight: pygments
    global_numbering: true
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  cache = FALSE,
  fig.align = "center",
  fig.width = 5,
  fig.height = 4,
  dev = "png"
)
options(scipen = 999)
```

# Spring 2022

## Summary of Changes Since Last Time

Several of the lecture videos were completely remade as a result of revisiting
and revising large parts of some sections of the course. A few demanding quiz
questions were also removed to lower the overall difficulty of the course.

## Summary of Students' Evaluation of the Course

Overall the student's responded favorably to the course. Out of the
24 respondents' impressions, 16 were "excellent", 7 "very good" and 1 "good".
Among the most highly valued parts of the course was the pre-recorded lectures
and general quality of the content of the course. When it comes to things
students thought would improve the course, students wished for a slightly lower
overall course load, better course literature, and more content to support 
more difficult parts of the course.

## Summary of Teachers' Overall Assessment

I thought the course went well overall and that the changes introduced all
turned out quite well. The lowered difficulty and course load seem to have had
some effect, with a higher proportion of students finishing the course. For
some reason, however, the course activity on the course was lower than usual.
For the last few workshop sessions, only a single person attended. There was also
less activity on the course forum (slack workspace) than last time. 

## Course Director's Reflections on the Course Implementation and Results

There were a few areas where student's repeatedly struggled throughout the
assignments, such as formatting figures properly: in particular, writing good
captions and sizing figures correctly. It is also clear that quite a few
students struggle or do not find time to deal with the last module that
contains the more difficult parts of the course. This material is not
handled in the assignments, which might create less incentive for students to
finish. There were also a few errors in the quizzes, which created dismay for
some students. Finally, it is clear that some students do not treat peer reviews
seriously and miss obvious errors in the reports.

## Course Director's Proposals for Changes

- Lower the number of assignments from 4 to 3 but make sure that all of the
  modules are covered in the assignments. 
- Change course literature to Kieran Healy's book "Data Visualization"
- Change grading of quizzes to having to complete every quiz (say minimum 50% of
  points on each quiz) but increase the
  number of trials.
- Require a general comment from each peer reviewer in addition to filling out
  the rubric.
- Add additional material on writing good captions, but be less stringent about
  captions when evaluating reports.

# Fall 2021

## Feedback

Out of 19 respondents, one gave the course a "satisfactory" score,
5 "very good", and 13 "excellent". As before, most of the respondents
were equally positive for most of the other questions. The students
reported that they spent, on average, 13.1 hours of work each week on the
course.

As far as constructive feedback goes, the most common issue was
that people thought the course was too demanding for the amount of credits.
There were other suggestions and feedback as well, but none of it was
shared between the participants.

## Changes in Response to Feedback

Several of the more demanding quiz questions have now been removed and 
others have been simplified. A few smaller parts of the course have been
altogether removed. As a result, several of the lecture videos have been
revised.

# Spring 2021

## Feedback

Among the 19 respondents, one gave the course a "sufficient" score, 4 "very
good", and 14 "excellent". Most of the respondents were equally positive for
most other questions except for the one regarding literature, which was regarded
as "sufficient" by 2, "good" by 6, "very good" by 4, "excellent" by 5, and
"don't know" by 2. Everyone except one respondent reported that they spent
between 0 and 17 hours per week on the course. The mean amount of time spent
was just below 10 hours.

When it comes to constructive feedback, here are a few things that students
thought might improve the course:

- coding videos,
- more time for the project,
- more theory and tools for data wrangling,
- better overview of course content, and
- less assignments and quizzes in general.

## Changes in Response to Feedback

Several coding videos were added and also a course overview. Some of the
quiz questions were simplified or removed. One assignment was completely
remade and another majorly revised.

# Fall 2020

Feedback on the course was positive across all items in the course evaluation.
We received one specific request, which was to make the workshops (help 
sessions) weekly instead of bi-weekly.

## Changes in Response to Feedback

The workshops have been changed to be held on a weekly basis instead. Many
small changes to the course content and fixes to errors in the quizzes.
